### ISSUE TITLE
New Flathub Screenshots

### ISSUE THREAD

**Issue by Byrdg** [flathub/org.kde.ktuberling#47]
Hey, I have these screenshots (attached) that I think are better than the current one because they are more updated and align more on how the app looks now. If its OK to update them, can you please point me to the appdata XML source or update them?"

![Screenshot from 2021-11-11 12-22-56](https://user-images.githubusercontent.com/94136706/141367815-0579a0d0-0e2d-42c2-bc5d-2eb7e31db2ff.png)
![Screenshot from 2021-11-11 12-19-44](https://user-images.githubusercontent.com/94136706/141367790-c85245e6-db9d-4e19-a644-2b70c79a3714.png)
![Screenshot from 2021-11-11 12-22-07](https://user-images.githubusercontent.com/94136706/141367805-b463b330-ee2a-48a8-9207-7343ddeac925.png)

**Comment by tsdgeos** [comment]
Appdata is https://invent.kde.org/games/ktuberling
Screenshots are https://invent.kde.org/websites/product-screenshots
