### ISSUE TITLE
Update to 18.08.2

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.kde.ktuberling#6]

**Comment by eszlari** [comment]
Looking at the commit log (https://github.com/KDE/ktuberling/commits/Applications/18.08), it seems there has been no big changes.

**Comment by tsdgeos** [comment]
18.08.2 is not even released yet.

**Comment by eszlari** [comment]
https://github.com/flathub/org.kde.ktuberling/commit/5f1d17268f59f9b2699c2dba9c2b399c17842592
